name: Run after Push workflow
on:
  workflow_run:
    workflows: ["Push"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say Push Workflow Completed
        run: echo "âœ… The Push workflow has been completed! ðŸŽ‰ðŸŽ‰"