name: External API Triggered Workflow

on:
  repository_dispatch:
    types: [print-payload]

jobs:
  print-payload:
    runs-on: ubuntu-latest
    steps:
      - name: Print Payload
        run: echo "âœ…ðŸŽ‰ ${{ github.event.client_payload.name }} make ${{ github.event.client_payload.action }}"
