name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Your name"
        required: true
        default: "Raed"
        type: choice
        options:
          - Raed
          - Ahmed
          - Mohamed
          - Sayed
          - Reda

jobs:
  print-name:
    runs-on: ubuntu-latest
    steps:
      - name: Print name
        run: echo "ðŸŽ‰ðŸŽ‰ Hello ${{ github.event.inputs.name }}"